export type Product = {
  id: string;
  slug: string;
  title: string;
  brand: string;
  category: string;
  description: string;
  image: string;
  amazonUrl: string;
  originalPrice: number;
  price: number;
  currency: string;
  rating: number;
  reviewCount: number;
  badges: string[];
  pros: string[];
  cons: string[];
  specs: Record<string, string | undefined>;
  featured?: boolean;
  trending?: boolean;
  editorChoice?: boolean;
};